blank_issues_enabled: true
contact_links:
  - name: Dash Core Security Policy
    url: https://github.com/dashpay/dash/blob/master/SECURITY.md
    about: View security policy
  - name: Dash Core Developers
    url: https://www.dash.org
    about: Dash Core homepage
